### ISSUE TITLE
What is introspection should i want to enable or disable 

### ISSUE THREAD

**Issue by Demonbruster** [jherr/graphql-jwt-speedrun#1]

**Comment by Demonbruster** [comment]
@jherr

**Comment by jherr** [comment]
Introspection in GraphQL terms is the functionality that the server provides to return the schema metadata for the GraphQL server itself so that It can be used by tools like the GraphQL Code Generator or GraphIQL. You should enable it for developers, and probably disable it in production, unless you want the GraphQL server to be the public API layer for your company and as such with Introspection you get documentation of the API for "free".
